name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install pom.xml
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.4
      with: 
       name: https://hub.docker.com/repository/docker/shashanksdixit
       username: ${{ secrets.dockerusername }} 
       password: ${{ secrets.dockerpassword }} 
